config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls', namespace='diary')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from diary.apps import DiaryConfig
from diary.views import EntryListView, EntryDetailView, EntryCreateView, EntryUpdateView, EntryDeleteView

app_name = DiaryConfig.name

urlpatterns = [
    path('entries/', EntryListView.as_view(), name='entries'),
    path('entry/<int:pk>', EntryDetailView.as_view(), name='entry'),
    path('create_entry/', EntryCreateView.as_view(), name='create_entry'),
    path('update_entry/<int:pk>', EntryUpdateView.as_view(), name='update_entry'),
    path('delete_entry/<int:pk>', EntryDeleteView.as_view(), name='delete_entry'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import GeneratePasswordView, RegisterView, email_verification, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html', next_page='diary:entries'), name='login'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('generate/', GeneratePasswordView.as_view(), name='generate'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

diary/models.py
from django.db import models

from config.settings import AUTH_USER_MODEL

NULLABLE = {'null': True, 'blank': True}


class Entry(models.Model):
    """Класс, описывающий информацию о записях в дневнике"""
    title = models.CharField(max_length=150, verbose_name='заголовок')
    body = models.TextField(verbose_name='cодержимое')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения', **NULLABLE)
    image = models.ImageField(verbose_name='изображение', **NULLABLE)
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'

diary/forms.py
from django.forms import ModelForm

from diary.models import Entry


class EntryForm(ModelForm):

    class Meta:
        model = Entry
        fields = [
            'title',
            'body',
            'image',
        ]

diary/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from diary.forms import EntryForm
from diary.models import Entry
from diary.services import get_cashe_entry_list, get_cashe_entry


class EntryListView(LoginRequiredMixin, ListView):
    """Контроллер списка записей"""
    model = Entry
    extra_context = {
        'title': 'Записи'
    }
    paginate_by = 9

    def get_paginate_by(self, queryset):
        """Возвращает список записей по страницам"""
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_queryset(self):
        """Возвращает список записей в соответствии с поиском"""
        query = self.request.GET.get('search', None)
        object_list = Entry.objects.filter(owner=self.request.user)
        if query:
            object_list = object_list.filter(
                Q(title__icontains=query) | Q(body__icontains=query)
            )
        return object_list

    def get_context_data(self, **kwargs):
        """Возвращает закешированный список записей"""
        context_data = super().get_context_data(**kwargs)
        context_data['entries'] = get_cashe_entry_list()
        return context_data


class EntryDetailView(UserPassesTestMixin, DetailView):
    """Контроллер просмотра одной записи"""
    model = Entry

    def get_context_data(self, **kwargs):
        """Возвращает наименование страницы и закешированную запись"""
        context_data = super().get_context_data(**kwargs)
        entry = self.get_object()
        context_data['entry'] = get_cashe_entry(entry.pk)
        context_data['title'] = entry.title
        return context_data

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class EntryCreateView(CreateView):
    """Контроллер создания новой записи"""
    model = Entry
    form_class = EntryForm
    extra_context = {
        'title': 'Создание записи'
    }

    def form_valid(self, form):
        """ Возвращает переход на страницу с записью, после ее создания"""
        entry = form.save()
        user = self.request.user
        entry.owner = user
        entry.save()
        return redirect('diary:entry', pk=entry.pk)


class EntryUpdateView(UserPassesTestMixin, UpdateView):
    """Контроллер изменения записи"""
    model = Entry
    form_class = EntryForm
    extra_context = {
        'title': 'Редактирование записи'
    }

    def get_success_url(self):
        """Возвращает переход на страницу с записью, если форма валидна"""
        return reverse('diary:entry', args=[self.kwargs.get('pk')])

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class EntryDeleteView(UserPassesTestMixin, DeleteView):
    """Контроллер удаления записи"""
    model = Entry
    success_url = reverse_lazy('diary:entries')

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user

diary/templates/diary/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {{title}} </title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/headers.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

    </style>
</head>

<body>

<main>
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                {% if user.is_authenticated %}
                <a href="{% url 'diary:entries' %}"
                   class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="{% static 'image/11.png' %}" width="40">
                    <span class="fs-4">Мой дневник</span>
                </a>
                {% else %}
                <img src="{% static 'image/11.png' %}" width="40">
                <span class="fs-4">Мой дневник</span>
                {% endif %}
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                </ul>
                <div class="text-end">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}" type="button" class="btn btn-outline-light me-2">Выйти</a>
                    <a href="{% url 'users:profile' user.pk %}" type="button" class="btn btn-warning">Профиль</a>
                    {% else %}
                    <a href="{% url 'users:login' %}" type="button" class="btn btn-outline-light me-2">Войти</a>
                    <a href="{% url 'users:register' %}" type="button" class="btn btn-warning">Регистрация</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

diary/templates/diary/entry_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-3">
        </div>
        <div class="col-6"><br><br><br>
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Вы действительно хотите удалить запись <b>"{{object | truncatechars:30}}"</b> ?</p>
                        <button class="btn btn-warning" type="submit">Подтвердить</button>
                        <input type="button" class="btn btn-outline-dark" onclick="history.back();"
                               value="Отмена"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/entry_detail.html
{% extends 'diary/base.html' %}
{% block content %}
{% load image_filter %}
<div class="album py-5 bg-light">
    <div class="container">
        <input type="button" class="btn btn-sm btn-outline-dark" onclick="history.back();" value="Назад"/>
        <a href="{% url 'diary:entries' %}" type="button"
           class="btn btn-sm btn-outline-dark">Выйти</a><br><br>
        <div class="row row-cols-1 g-3">
            <div class="d-grid gap-2 col-10 mx-auto">
                <div class="card shadow-sm">
                    {% if entry.image %}
                    <img src="{{ entry.image | mymedia }}">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text"><b>{{ entry }}</b></p>
                        <p class="card-text">{{ entry.body }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'diary:update_entry' entry.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                <a href="{% url 'diary:delete_entry' entry.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Удалить</a>
                            </div>
                            <small class="text-muted">
                                {{ entry.updated_at | date:'d-m-Y H:i'}}
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/entry_form.html
{% extends 'diary/base.html' %}
{% block content %}
<br><br><br>
<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            {% load crispy_forms_tags %}
            <div class="col-6">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button class="btn btn-warning" type="submit">Сохранить</button>
                <input type="button" class="btn btn-outline-dark" onclick="history.back();" value="Отмена"/>
            </div>
        </div>
    </div>
</form>


{% endblock %}

diary/templates/diary/entry_list.html
{% extends 'diary/base.html' %}
{% block content %}
{% load image_filter %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="d-grid gap-2 col-3 mx-auto">
            <form class="col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <form class="d-flex" role="search" method="get" action="{% url 'diary:entries' %}">
                    <input name="search" type="search" class="form-control form-control-white" placeholder="Поиск..."
                           aria-label="Search">
                </form>
            </form>
        </div>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'diary:create_entry' %}" type="button"
               class="btn btn-warning"> + Добавить запись </a>
        </div><br>
        {% if object_list %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for entry in page_obj %}
            <div class="col">
                <div class="card shadow-sm">
                    {% if not entry.image %}
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="150"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">Фото отсутствует</text>
                    </svg>
                    {% else %}
                    <img src="{{ entry.image | mymedia }}" height="150">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{ entry | truncatechars:40 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'diary:entry' entry.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Открыть</a>
                            <small class="text-muted">
                                {{ entry.updated_at | date:'d-m-Y H:i'}}
                            </small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <br>
        <p class="lead">Записи отсутствуют.</p>
        <input type="button" class="btn btn-sm btn-outline-dark" onclick="history.back();" value="Назад"/>
        <br><br><br><br><br><br><br><br><br>
        {% endif %}
    </div>
</div>

<br/>
<div class="d-grid gap-2 col-11 mx-auto">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% for p in page_obj.paginator.page_range %}
            <li class="page-item">
                <a class="page-link text-dark" href="?page= {{ p }}">
                    {{ p }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}