config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls', namespace='diary')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from diary.apps import DiaryConfig
from diary.views import EntryListView, EntryDetailView, EntryCreateView, EntryUpdateView, EntryDeleteView

app_name = DiaryConfig.name

urlpatterns = [
    path('entries/', EntryListView.as_view(), name='entries'),
    path('entry/<int:pk>', EntryDetailView.as_view(), name='entry'),
    path('create_entry/', EntryCreateView.as_view(), name='create_entry'),
    path('update_entry/<int:pk>', EntryUpdateView.as_view(), name='update_entry'),
    path('delete_entry/<int:pk>', EntryDeleteView.as_view(), name='delete_entry'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import GeneratePasswordView, RegisterView, email_verification, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html', next_page='diary:entries'), name='login'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('generate/', GeneratePasswordView.as_view(), name='generate'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from diary.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    firstname = models.CharField(max_length=35, verbose_name='имя', **NULLABLE)
    last_name = models.CharField(max_length=35, verbose_name='фамилия', **NULLABLE)
    birthdate = models.DateField(verbose_name='дата рождения', **NULLABLE)

    token = models.CharField(max_length=100, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm
from django.core.exceptions import ObjectDoesNotExist

from users.models import User


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'firstname', 'last_name', 'birthdate',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class YourPasswordResetForm(PasswordResetForm):

    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        try:
            email = self.cleaned_data.get('email')
            user = User.objects.get(email=email)
            if user:
                return user
        except ObjectDoesNotExist:
            raise forms.ValidationError('Данный email не зарегистрирован')

users/views.py
import secrets

from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from config import settings
from users.forms import RegisterForm, UserProfileForm, YourPasswordResetForm
from users.models import User


class RegisterView(CreateView):
    """Контроллер регистрации пользователя"""
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Отправка подтверждения регистрации по электронной почте"""
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/email-confirm/{token}'
        send_mail(
            'Регистрация "Мой дневник"',
            f'Для подтверждения регистрации перейдите по ссылке {url}',
            settings.EMAIL_HOST_USER,
            [user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    """Проверка электронной почты"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class GeneratePasswordView(PasswordResetView):
    """Класс генерации нового пароля"""
    form_class = YourPasswordResetForm
    template_name = 'users/generate.html'

    def form_valid(self, form):
        """Генерация нового пароля с отправкой по электронной почте"""
        if form.is_valid():
            user = form.clean_email()
            password = User.objects.make_random_password(12)
            user.set_password(password)
            user.save()
            send_mail(
                'Смена пароля "Мой дневник"',
                f'Ваш новый пароль: {password}',
                settings.EMAIL_HOST_USER,
                [user.email],
            )
            return redirect(reverse("users:login"))


class ProfileView(UpdateView):
    """Класс редактирования профиля"""
    model = User
    form_class = UserProfileForm

    def get_success_url(self):
        """Направляет на указанную страницу если форма валидна"""
        return reverse('users:profile', args=[self.kwargs.get('pk')])

users/templates/users/generate.html
{% extends 'diary/base.html' %}
{% block content %}


<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            {% load crispy_forms_tags %}
            <div class="col-4">
            </div>
            <div class="col-3">
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <p class="lead">Восстановление пароля</p>
                </div>
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button class="btn btn-warning" type="submit">Отправить</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

users/templates/users/login.html
{% extends 'diary/base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            {% load crispy_forms_tags %}
            <div class="col-4">
            </div>
            <div class="col-3">
                <br><br>
                <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <p class="lead">Вход</p>
                </div>
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button class="btn btn-warning" type="submit">Войти</button>
                <a class="p-2 btn-outline-primary" href="{% url 'users:generate' %}">Восстановить пароль</a>
            </div>
        </div>
    </div>
</form>

{% endblock %}

users/templates/users/register.html
{% extends 'diary/base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            {% load crispy_forms_tags %}
            <div class="col-4">
            </div>
            <div class="col-3">
                <div class="pricing-header pt-md-5 mx-auto text-center">
                    <p class="lead">Регистрация</p>
                </div>
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button class="btn btn-warning" type="submit">Отправить</button>
                <br><br>
            </div>
        </div>
    </div>
</form>

{% endblock %}

users/templates/users/user_form.html
{% extends 'diary/base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            {% load crispy_forms_tags %}
            <div class="col-4">
            </div>
            <div class="col-3">
                <div class="pricing-header pt-md-5 mx-auto text-center">
                    <p class="lead">Профиль</p>
                </div>
                {% csrf_token %}
                {{ form|crispy }}<br>
                <button class="btn btn-warning" type="submit">Сохранить</button>
                <br><br>
            </div>
        </div>
    </div>
</form>

{% endblock %}